name: Golang
on: push
jobs:
    test:
        name: Unit Testing

        runs-on: ubuntu-latest
        container: golang:1.22
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Run Unit Tests
              run: GOOS=linux GOARCH=amd64 go test
        
            - name: Run Vet
              run: |
                go vet ./...

    deploy:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        needs: test
        if: startsWith(github.ref, 'refs/tags')
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5.5.1
              with:
                images: narratives/parcel-app
